document.write([
    '<ul class="zyMenu zyMenuFixed" id="zyMenu">',
    '<li>',
    '<a href="index.html" data-page-name="index">',
    '<span class="zyTop">Home</span>',
    '乡•首页',
    '</a>',
    '</li>',
    '<li>',
    '<a href="about.html" data-page-name="about">',
    '<span class="zyTop">About us</span>',
    '关于•乡HOME',
    '</a>',
    '</li>',
    '<li class="zyLogo">',
    '<a href="index.html">',
    '<img src="static/images/src/logo.png">',
    '</a>',
    '</li>',
    '<li>',
    '<a href="fashion.html" data-page-name="fashion">',
    '<span class="zyTop">Editor\'s Picks</span>',
    '乡•风尚精选',
    '</a>',
    '</li>',
    '<li>',
    '<a href="original.html" data-page-name="original">',
    '<span class="zyTop">Original Design</span>',
    '乡•原创精选',
    '</a>',
    '</li>',
    '</ul>'].join(""));